export const FETCH_WIZARDS_LOADING = 'FETCH_WIZARDS_LOADING';
export const FETCH_WIZARDS_SUCCESS = 'FETCH_WIZARDS_SUCCESS';
export const FETCH_WIZARDS_ERROR = 'FETCH_WIZARDS_ERROR';

export const FETCH_ETH_PROVIDER_SUCCESS = 'FETCH_ETH_PROVIDER_SUCCESS';
export const FETCH_ETH_PROVIDER_ERROR = 'FETCH_ETH_PROVIDER_ERROR';
  
export const CREATE_WIZARD_SUCCESS = 'CREATE_WIZARD_SUCCESS';
export const CREATE_WIZARD_ERROR = 'CREATE_WIZARD_ERROR';

export const REGISTER_WIZARD = 'REGISTER_WIZARD';
export const DEREGISTER_WIZARD = 'DEREGISTER_WIZARD';
export const FETCH_REGISTERED_WIZARDS = 'FETCH_REGISTERED_WIZARDS';
export const FETCH_REGISTERED_WIZARDS_LOADING = 'FETCH_REGISTERED_WIZARDS_LOADING';
export const FETCH_REGISTERED_WIZARDS_ERROR = 'FETCH_REGISTERED_WIZARDS_ERROR';
