export const FETCH_WIZARDS_LOADING = 'FETCH_WIZARDS_LOADING';
export const FETCH_WIZARDS_SUCCESS = 'FETCH_WIZARDS_SUCCESS';
export const FETCH_WIZARDS_ERROR = 'FETCH_WIZARDS_ERROR';

export const FETCH_ETH_PROVIDER_SUCCESS = 'FETCH_ETH_PROVIDER_SUCCESS';
export const FETCH_ETH_PROVIDER_ERROR = 'FETCH_ETH_PROVIDER_ERROR';
  
export const CREATE_WIZARD_SUCCESS = 'CREATE_WIZARD_SUCCESS';
export const CREATE_WIZARD_ERROR = 'CREATE_WIZARD_ERROR';
